<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\KlentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/login2', [AuthController::class,'login2']);
Route::get('a', [AuthController::class,'typpe'])->name('typpe');
Route::get('exports', [AuthController::class,'exports'])->name('exports');
Route::get('exports2', [AuthController::class,'exports2'])->name('exports2');
Route::get('exports2dok', [AuthController::class,'exports2dok'])->name('exports2dok');
Route::get('exports3', [AuthController::class,'exports3'])->name('exports3');
Route::get('exports3dok', [AuthController::class,'exports3dok'])->name('exports3dok');
Route::get('exports4', [AuthController::class,'exports4'])->name('exports4');
Route::get('exports4dok', [AuthController::class,'exports4dok'])->name('exports4dok');
Route::get('exports5', [AuthController::class,'exports5'])->name('exports5');
Route::get('exports5dok', [AuthController::class,'exports5dok'])->name('exports5dok');
Route::get('exports6', [AuthController::class,'exports6'])->name('exports6');
Route::get('exports6dok', [AuthController::class,'exports6dok'])->name('exports6dok');
Route::get('exports7', [AuthController::class,'exports7'])->name('exports7');
Route::get('exports7dok', [AuthController::class,'exports7dok'])->name('exports7dok');
Route::get('exports8', [AuthController::class,'exports8'])->name('exports8');
Route::get('exports8dok', [AuthController::class,'exports8dok'])->name('exports8dok');
Route::get('exports9', [AuthController::class,'exports9'])->name('exports9');
Route::get('deeletkarzina', [AuthController::class,'deeletkarzina'])->name('deeletkarzina');
Route::get('deeletkarzinadok', [AuthController::class,'deeletkarzinadok'])->name('deeletkarzinadok');

Route::post('imports', [AuthController::class,'imports'])->name('imports');
Route::post('import2', [AuthController::class,'import2'])->name('import2');
Route::post('import2dok', [AuthController::class,'import2dok'])->name('import2dok');
Route::post('import3', [AuthController::class,'import3'])->name('import3');
Route::post('import3dok', [AuthController::class,'import3dok'])->name('import3dok');
Route::post('import4', [AuthController::class,'import4'])->name('import4');
Route::post('import4dok', [AuthController::class,'import4dok'])->name('import4dok');
Route::post('import5', [AuthController::class,'import5'])->name('import5');
Route::post('import5dok', [AuthController::class,'import5dok'])->name('import5dok');
Route::post('import6', [AuthController::class,'import6'])->name('import6');
Route::post('import6dok', [AuthController::class,'import6dok'])->name('import6dok');
Route::post('import7', [AuthController::class,'import7'])->name('import7');
Route::post('import7dok', [AuthController::class,'import7dok'])->name('import7dok');
Route::post('storeishchi', [KlentController::class, 'storeishchi'])->name('storeishchi');
Route::post('storeadmin', [KlentController::class, 'storeadmin'])->name('storeadmin');
Route::get('live_ishchi', [KlentController::class, 'live_ishchi'])->name('live_ishchi');
Route::get('live_admin', [KlentController::class, 'live_admin'])->name('live_admin');
Route::get('showishchi/{id}', [KlentController::class, 'showishchi']);
Route::get('srocrow', [AuthController::class,'srocrow'])->name('srocrow');
Route::get('srocrowdok', [AuthController::class,'srocrowdok'])->name('srocrowdok');
Route::post('profilimage', [AuthController::class, 'profilimage'])->name('profilimage');
Route::get('imagesprofil', [AuthController::class, 'imagesprofil'])->name('imagesprofil');

Route::get('showadmin/{id}', [KlentController::class, 'showadmin']);
Route::post('deleteishchi/{id}', [KlentController::class, 'deleteishchi']);
Route::post('deleteadmin/{id}', [KlentController::class, 'deleteadmin']);

Route::resource('posts', KlentController::class);
Route::post('login-user', [AuthController::class,'loginuser'])->name('login-user');
Route::get('/logaut', [AuthController::class,'logaut']);
// Route::get('/profil', [AuthController::class,'profil'])->name('profil');
Route::get('/setting', [AuthController::class,'setting'])->name('setting');


Route::group(['middleware'=>['isLog']], function (){
    Route::get('/', [AuthController::class,'login']);
    Route::get('/glavninachal', [AuthController::class,'dashbord']);
});

Route::get('tavar_live', [KlentController::class, 'tavar_live'])->name('tavar_live');
Route::get('tavar_livedok', [KlentController::class, 'tavar_livedok'])->name('tavar_livedok');
Route::get('tavar2_live', [KlentController::class, 'tavar2_live'])->name('tavar2_live');
Route::get('tavar2_livedok', [KlentController::class, 'tavar2_livedok'])->name('tavar2_livedok');
Route::get('live_adress', [KlentController::class, 'live_adress'])->name('live_adress');
Route::get('live_adressdok', [KlentController::class, 'live_adressdok'])->name('live_adressdok');
Route::get('live_clent', [KlentController::class, 'live_clent'])->name('live_clent');
Route::get('ichkitavartbody', [KlentController::class, 'ichkitavartbody'])->name('ichkitavartbody');
Route::get('datasearche', [KlentController::class, 'datasearche'])->name('datasearche');
Route::get('tiklaslar', [KlentController::class, 'tiklaslar'])->name('tiklaslar');
Route::get('live_clentdok', [KlentController::class, 'live_clentdok'])->name('live_clentdok');
Route::get('index', [KlentController::class, 'index'])->name('index');
Route::get('indextip', [KlentController::class, 'indextip'])->name('indextip');
Route::get('tidtolov', [KlentController::class, 'tidtolov'])->name('tidtolov');
Route::get('tidtolovdok', [KlentController::class, 'tidtolovdok'])->name('tidtolovdok');
Route::post('tolash', [KlentController::class, 'tolash'])->name('tolash');
Route::post('tolashdok', [KlentController::class, 'tolashdok'])->name('tolashdok');
Route::post('storead', [KlentController::class, 'storead'])->name('storead');
Route::post('storedok', [KlentController::class, 'storedok'])->name('storedok');
Route::get('show/{id}', [KlentController::class, 'show']);
Route::get('showdok/{id}', [KlentController::class, 'showdok']);
Route::post('update', [KlentController::class, 'update'])->name('update');
Route::post('delete/{id}', [KlentController::class, 'destroy']);
Route::post('deletedok/{id}', [KlentController::class, 'destroydok']);

Route::post('store2', [KlentController::class, 'store2'])->name('store2');
Route::post('store2dok', [KlentController::class, 'store2dok'])->name('store2dok');
Route::post('store2tip', [KlentController::class, 'store2tip'])->name('store2tip');
Route::post('store2tipdok', [KlentController::class, 'store2tipdok'])->name('store2tipdok');
Route::post('update2', [KlentController::class, 'update2'])->name('update2');
Route::post('update2dok', [KlentController::class, 'update2dok'])->name('update2dok');
Route::post('updateer2', [KlentController::class, 'updateer2'])->name('updateer2');
Route::post('updateer2dok', [KlentController::class, 'updateer2dok'])->name('updateer2dok');
Route::get('iidd3', [KlentController::class, 'iidd3'])->name('iidd3');
Route::get('iidd4', [KlentController::class, 'iidd4'])->name('iidd4');
Route::get('show2', [KlentController::class, 'show2'])->name('show2');
Route::get('show2dok', [KlentController::class, 'show2dok'])->name('show2dok');
Route::get('shower2/{id}', [KlentController::class, 'shower2']);
Route::get('shower2dok/{id}', [KlentController::class, 'shower2dok']);
Route::post('delete2/{id}', [KlentController::class, 'delete2']);
Route::post('delete2dok/{id}', [KlentController::class, 'delete2dok']);
Route::post('deleteer2dok/{id}', [KlentController::class, 'deleteer2']);
Route::post('deleteer2dok/{id}', [KlentController::class, 'deleteer2dok']);
Route::get('edit3', [KlentController::class, 'edit3'])->name('edit3');

Route::post('store3', [KlentController::class, 'store3'])->name('store3');
Route::post('store3create', [KlentController::class, 'store3create'])->name('store3create');
Route::post('storedd3', [KlentController::class, 'storedd3'])->name('storedd3');
Route::post('store3dok', [KlentController::class, 'store3dok'])->name('store3dok');
Route::post('updates', [KlentController::class, 'updates'])->name('updates');
Route::post('updatesdok', [KlentController::class, 'updatesdok'])->name('updatesdok');
Route::get('edit4', [KlentController::class, 'edit4'])->name('edit4');
Route::get('edit4dok', [KlentController::class, 'edit4dok'])->name('edit4dok');
Route::post('delete3/{id}', [KlentController::class, 'delete3']);
Route::post('delete3dok/{id}', [KlentController::class, 'delete3dok']);
Route::post('tiklash/{id}', [KlentController::class, 'tiklash']);
Route::post('tiklashdok/{id}', [KlentController::class, 'tiklashdok']);
Route::post('deleetemnu/{id}', [KlentController::class, 'deleetemnu']);
Route::post('deleetemnudok/{id}', [KlentController::class, 'deleetemnudok']);
Route::get('edit5', [KlentController::class, 'edit5'])->name('edit5');
Route::post('store4', [KlentController::class, 'store4'])->name('store4');

Route::get('adress', [KlentController::class, 'adress'])->name('adress');
Route::get('ombor', [KlentController::class, 'ombor'])->name('ombor');
Route::get('index2', [KlentController::class, 'index2'])->name('index2');

Route::post('pastavka', [KlentController::class, 'pastavka'])->name('pastavka');
Route::post('pastavkadok', [KlentController::class, 'pastavkadok'])->name('pastavkadok');
Route::get('past', [KlentController::class, 'past'])->name('past');
Route::get('show3/{id}', [KlentController::class, 'show3']);
Route::post('pastavkaupdate', [KlentController::class, 'pastavkaupdate'])->name('pastavkaupdate');
Route::post('pastavkaupdatedok', [KlentController::class, 'pastavkaupdatedok'])->name('pastavkaupdatedok');
Route::post('delete4/{id}', [KlentController::class, 'delete4']);

Route::get('clents', [KlentController::class, 'clents'])->name('clents');
Route::post('sazdat', [KlentController::class, 'sazdat'])->name('sazdat');
Route::post('sazdatdok', [KlentController::class, 'sazdatdok'])->name('sazdatdok');
Route::post('belgila', [KlentController::class, 'belgila'])->name('belgila');
Route::post('belgiladok', [KlentController::class, 'belgiladok'])->name('belgiladok');
Route::get('kursm', [KlentController::class, 'kursm'])->name('kursm');
Route::get('kursmdok', [KlentController::class, 'kursmdok'])->name('kursmdok');
Route::get('belgi2', [KlentController::class, 'belgi2'])->name('belgi2');
Route::get('belgi2dok', [KlentController::class, 'belgi2dok'])->name('belgi2dok');
Route::get('usdkurd2', [KlentController::class, 'usdkurd2'])->name('usdkurd2');
Route::get('dollarkurs', [KlentController::class, 'dollarkurs'])->name('dollarkurs');
Route::get('usdkurd2dok', [KlentController::class, 'usdkurd2dok'])->name('usdkurd2dok');
Route::get('/sotuv',[KlentController::class, 'sotuv'])->name('sotuv');
Route::get('/lister',[KlentController::class, 'lister'])->name('lister');
Route::get('/sotuvdok',[KlentController::class, 'sotuvdok'])->name('sotuvdok');
Route::get('/live_search',[KlentController::class, 'live_search'])->name('live_search');
Route::get('/live_searchdokon',[KlentController::class, 'live_searchdokon'])->name('live_searchdokon');
Route::get('/live_searchdok',[KlentController::class, 'live_searchdok'])->name('live_searchdok');
Route::get('/sqladiskizapas',[KlentController::class, 'sqladiskizapas'])->name('sqladiskizapas');
Route::get('/sqladiskizapasdok',[KlentController::class, 'sqladiskizapasdok'])->name('sqladiskizapasdok');
Route::get('/sqladiskizapas2',[KlentController::class, 'sqladiskizapas2'])->name('sqladiskizapas2');
Route::get('/sqladiskizapas2dok',[KlentController::class, 'sqladiskizapas2dok'])->name('sqladiskizapas2dok');
Route::get('/tbody3table',[KlentController::class, 'tbody3table'])->name('tbody3table');
Route::get('/tbody3tabledok',[KlentController::class, 'tbody3tabledok'])->name('tbody3tabledok');
Route::get('/tbody3table2',[KlentController::class, 'tbody3table2'])->name('tbody3table2');
Route::get('/tbody3table2dok',[KlentController::class, 'tbody3table2dok'])->name('tbody3table2dok');
Route::post('plus', [KlentController::class, 'plus'])->name('plus');
Route::post('plusdok', [KlentController::class, 'plusdok'])->name('plusdok');
Route::post('minus', [KlentController::class, 'minus'])->name('minus');
Route::post('minusdok', [KlentController::class, 'minusdok'])->name('minusdok');
Route::post('udalit', [KlentController::class, 'udalit'])->name('udalit');
Route::post('udalitdok', [KlentController::class, 'udalitdok'])->name('udalitdok');
Route::post('yangilash', [KlentController::class, 'yangilash'])->name('yangilash');
Route::post('yangilashdok', [KlentController::class, 'yangilashdok'])->name('yangilashdok');
Route::post('tugle', [KlentController::class, 'tugle'])->name('tugle');
Route::post('tugledok', [KlentController::class, 'tugledok'])->name('tugledok');
Route::get('rachot', [KlentController::class, 'rachot'])->name('rachot');
Route::get('rachotdok', [KlentController::class, 'rachotdok'])->name('rachotdok');
Route::post('oplata', [KlentController::class, 'oplata'])->name('oplata');
Route::post('bot', [KlentController::class, 'bot'])->name('bot');
Route::post('botdok', [KlentController::class, 'botdok'])->name('botdok');
Route::get('bot2', [KlentController::class, 'bot2'])->name('bot2');
Route::get('bot2dok', [KlentController::class, 'bot2dok'])->name('bot2dok');
Route::post('oplatadok', [KlentController::class, 'oplatadok'])->name('oplatadok');
Route::post('zakazayt', [KlentController::class, 'zakazayt'])->name('zakazayt');
Route::post('zakazaytdok', [KlentController::class, 'zakazaytdok'])->name('zakazaytdok');

Route::post('data', [KlentController::class, 'data'])->name('data');
Route::get('tavar', [KlentController::class, 'tavar'])->name('tavar');
Route::get('tavardok', [KlentController::class, 'tavardok'])->name('tavardok');
Route::get('tavar_tip', [KlentController::class, 'tavar_tip'])->name('tavar_tip');
Route::get('nolas', [KlentController::class, 'nolas'])->name('nolas');
Route::get('tavar_tipdok', [KlentController::class, 'tavar_tipdok'])->name('tavar_tipdok');
Route::post('limither', [KlentController::class, 'limither'])->name('limither');
Route::get('statistika', [KlentController::class, 'statistika'])->name('statistika');
Route::get('statistik', [KlentController::class, 'statistik'])->name('statistik');
Route::get('statistikdok', [KlentController::class, 'statistikdok'])->name('statistikdok');
Route::get('statistik2', [KlentController::class, 'statistik2'])->name('statistik2');
Route::get('zzzz', [KlentController::class, 'zzzz'])->name('zzzz');
Route::get('zzzzdok', [KlentController::class, 'zzzzdok'])->name('zzzzdok');
Route::get('zzzzcli', [KlentController::class, 'zzzzcli'])->name('zzzzcli');
Route::get('zzzzclidok', [KlentController::class, 'zzzzclidok'])->name('zzzzclidok');
Route::get('zzzzaaaadok', [KlentController::class, 'zzzzaaaadok'])->name('zzzzaaaadok');
Route::get('zzzzaaaa', [KlentController::class, 'zzzzaaaa'])->name('zzzzaaaa');
Route::get('tavarvse', [KlentController::class, 'tavarvse'])->name('tavarvse');
Route::get('tavarvsedok', [KlentController::class, 'tavarvsedok'])->name('tavarvsedok');
Route::get('zzzzclick', [KlentController::class, 'zzzzclick'])->name('zzzzclick');
Route::get('zzzzclickdok', [KlentController::class, 'zzzzclickdok'])->name('zzzzclickdok');
Route::post('submitckicked', [KlentController::class, 'submitckicked'])->name('submitckicked');
Route::post('submitckickeddok', [KlentController::class, 'submitckickeddok'])->name('submitckickeddok');
Route::get('datasearchedok', [KlentController::class, 'datasearchedok'])->name('datasearchedok');
Route::post('search', [KlentController::class, 'search'])->name('search');
Route::post('searchdok', [KlentController::class, 'searchdok'])->name('searchdok');
Route::get('clent2', [KlentController::class, 'clent2'])->name('clent2');
Route::get('qaytaredit', [KlentController::class, 'qaytaredit'])->name('qaytaredit');
Route::get('qaytareditdok', [KlentController::class, 'qaytareditdok'])->name('qaytareditdok');
Route::get('qaytareditbirlam', [KlentController::class, 'qaytareditbirlam'])->name('qaytareditbirlam');
Route::get('qaytareditbirlamdok', [KlentController::class, 'qaytareditbirlamdok'])->name('qaytareditbirlamdok');
Route::post('vseclent', [KlentController::class, 'vseclent'])->name('vseclent');
Route::post('qaytar', [KlentController::class, 'qaytar'])->name('qaytar');
Route::post('qaytardok', [KlentController::class, 'qaytardok'])->name('qaytardok');
Route::post('qaytarbirlamchini', [KlentController::class, 'qaytarbirlamchini'])->name('qaytarbirlamchini');
Route::post('qaytarbirlamchinidok', [KlentController::class, 'qaytarbirlamchinidok'])->name('qaytarbirlamchinidok');
Route::post('vseclentdok', [KlentController::class, 'vseclentdok'])->name('vseclentdok');
Route::get('clent_tip', [KlentController::class, 'clent_tip'])->name('clent_tip');
Route::get('clent_tipdok', [KlentController::class, 'clent_tipdok'])->name('clent_tipdok');
Route::get('savdobirlamchi', [KlentController::class, 'savdobirlamchi'])->name('savdobirlamchi');
Route::get('vazvradspi', [KlentController::class, 'vazvradspi'])->name('vazvradspi');
Route::get('vazvradspidok', [KlentController::class, 'vazvradspidok'])->name('vazvradspidok');
Route::get('savdobirlamchidok', [KlentController::class, 'savdobirlamchidok'])->name('savdobirlamchidok');
Route::get('clents2', [KlentController::class, 'clents2'])->name('clents2');
Route::get('clents2aniq', [KlentController::class, 'clents2aniq'])->name('clents2aniq');
Route::get('clents2aniqdok', [KlentController::class, 'clents2aniqdok'])->name('clents2aniqdok');
Route::get('clents2dok', [KlentController::class, 'clents2dok'])->name('clents2dok');
Route::post('clents3', [KlentController::class, 'clents3'])->name('clents3');
Route::post('clents3dok', [KlentController::class, 'clents3dok'])->name('clents3dok');
Route::post('brlamclient', [KlentController::class, 'brlamclient'])->name('brlamclient');
Route::post('brlamclientdok', [KlentController::class, 'brlamclientdok'])->name('brlamclientdok');

Route::get('prodacha', [KlentController::class, 'prodacha'])->name('prodacha');
Route::get('sqlad.php', [KlentController::class, 'sqladiski'])->name('sqlad.php');
Route::post('otkazish', [KlentController::class, 'otkazish'])->name('otkazish');
Route::post('otkazishdok', [KlentController::class, 'otkazishdok'])->name('otkazishdok');
Route::get('malumotolish', [KlentController::class, 'malumotolish'])->name('malumotolish');
Route::get('malumotolishdok', [KlentController::class, 'malumotolishdok'])->name('malumotolishdok');
Route::post('plussqlad', [KlentController::class, 'plussqlad'])->name('plussqlad');
Route::post('plussqladdok', [KlentController::class, 'plussqladdok'])->name('plussqladdok');
Route::post('minussqlad', [KlentController::class, 'minussqlad'])->name('minussqlad');
Route::post('minussqladdok', [KlentController::class, 'minussqladdok'])->name('minussqladdok');
Route::post('udalitsqlad', [KlentController::class, 'udalitsqlad'])->name('udalitsqlad');
Route::post('udalitsqladdok', [KlentController::class, 'udalitsqladdok'])->name('udalitsqladdok');
Route::get('yangilashsqlad', [KlentController::class, 'yangilashsqlad'])->name('yangilashsqlad');
Route::get('yangilashsqladdok', [KlentController::class, 'yangilashsqladdok'])->name('yangilashsqladdok');
Route::post('saqlashsqlad', [KlentController::class, 'saqlashsqlad'])->name('saqlashsqlad');
Route::post('saqlashsqladdok', [KlentController::class, 'saqlashsqladdok'])->name('saqlashsqladdok');
Route::post('tayyorsqlad', [KlentController::class, 'tayyorsqlad'])->name('tayyorsqlad');
Route::post('tayyorsqladdok', [KlentController::class, 'tayyorsqladdok'])->name('tayyorsqladdok');
Route::get('iidd', [KlentController::class, 'iidd'])->name('iidd');
Route::get('toldirish', [KlentController::class, 'toldirish'])->name('toldirish');
Route::get('toldirishdok', [KlentController::class, 'toldirishdok'])->name('toldirishdok');
Route::get('tavardok_id2', [KlentController::class, 'tavardok_id2'])->name('tavardok_id2');
Route::get('tavardok_id', [KlentController::class, 'tavardok_id'])->name('tavardok_id');
Route::get('tavardokoption_id', [KlentController::class, 'tavardokoption_id'])->name('tavardokoption_id');

Route::get('/mijozlar.php', [AuthController::class, 'mijozlar'])->name('mijozlar');
Route::get('/usta.php', [AuthController::class, 'usta'])->name('usta');
Route::post('/usracreate.php', [AuthController::class, 'usracreate'])->name('usracreate');
Route::get('/editusta', [AuthController::class, 'editusta'])->name('editusta');
Route::post('/updateusta', [AuthController::class, 'updateusta'])->name('updateusta');
Route::post('/deleteusta', [AuthController::class, 'deleteusta'])->name('deleteusta');
Route::post('/store.php', [AuthController::class, 'store'])->name('store');
Route::get('/edit', [AuthController::class, 'edit'])->name('edit');
Route::post('/update', [AuthController::class, 'update'])->name('update');
Route::get('/search.php', [AuthController::class, 'search'])->name('search');
Route::get('/mijozsearch.php', [AuthController::class, 'mijozsearch'])->name('mijozsearch');
Route::post('/aloqa', [AuthController::class, 'aloqa'])->name('aloqa');
Route::post('/otkazishauth', [AuthController::class, 'otkazishauth'])->name('otkazishauth');
Route::get('/tayyor', [AuthController::class, 'tugatilgan'])->name('bajarilgan');
Route::get('/searchb', [AuthController::class, 'searchb'])->name('searchb');

Route::get('/mijjozz', [AuthController::class, 'mijjozz'])->name('mijjozz');
Route::get('/mijjozz2', [AuthController::class, 'mijjozz2'])->name('mijjozz2');
Route::get('/mijjozz3', [AuthController::class, 'mijjozz3'])->name('mijjozz3');
Route::get('/servislar', [AuthController::class, 'servislar'])->name('servislar');
Route::get('/vazvratspisk', [AuthController::class, 'vazvratspisk'])->name('vazvratspisk');
Route::get('kelgantovar2ajax', [KlentController::class, 'kelgantovar2ajax'])->name('kelgantovar2ajax');
Route::get('kelgantovar2', [KlentController::class, 'kelgantovar2'])->name('kelgantovar2');
Route::get('kelgantovar2ajaxdok', [KlentController::class, 'kelgantovar2ajaxdok'])->name('kelgantovar2ajaxdok');
Route::post('sinimayt', [KlentController::class, 'sinimayt'])->name('sinimayt');
Route::post('sinimaytdok', [KlentController::class, 'sinimaytdok'])->name('sinimaytdok');
Route::get('/rasxod', [KlentController::class, 'rasxod'])->name('rasxod');
Route::get('/getrasxod', [KlentController::class, 'getrasxod'])->name('getrasxod');
Route::get('/getrasxoddok', [KlentController::class, 'getrasxoddok'])->name('getrasxoddok');
Route::post('postrasxod', [KlentController::class, 'postrasxod'])->name('postrasxod');
Route::post('postrasxoddok', [KlentController::class, 'postrasxoddok'])->name('postrasxoddok');
Route::post('deletrasxod/{id}', [KlentController::class, 'deletrasxod']);
Route::post('deletrasxoddok/{id}', [KlentController::class, 'deletrasxoddok']);

Route::get('chd', [KlentController::class, 'chd'])->name('chd');
Route::get('chd2', [KlentController::class, 'chd2'])->name('chd2');
Route::get('chb', [KlentController::class, 'chb'])->name('chb');
Route::get('chb2', [KlentController::class, 'chb2'])->name('chb2');
Route::post('otmetka2', [KlentController::class, 'otmetka2'])->name('otmetka2');
Route::post('otmetka', [KlentController::class, 'otmetka'])->name('otmetka');

Route::get('/usersumma', [AuthController::class, 'usersumma'])->name('usersumma');
Route::get('/usersummadok', [AuthController::class, 'usersummadok'])->name('usersummadok');
Route::post('/aloxida', [AuthController::class, 'aloxida'])->name('aloxida');
Route::post('/aloxidadok', [AuthController::class, 'aloxidadok'])->name('aloxidadok');
Route::get('chddok', [KlentController::class, 'chddok'])->name('chddok');
Route::get('chd2dok', [KlentController::class, 'chd2dok'])->name('chd2dok');
Route::get('chbdok', [KlentController::class, 'chbdok'])->name('chbdok');
Route::get('chb2dok', [KlentController::class, 'chb2dok'])->name('chb2dok');
Route::post('otmetka2dok', [KlentController::class, 'otmetka2dok'])->name('otmetka2dok');
Route::post('otmetkadok', [KlentController::class, 'otmetkadok'])->name('otmetkadok');
Route::get('pribl.php', [KlentController::class, 'pribl'])->name('pribl.php');
Route::get('getel', [KlentController::class, 'getel'])->name('getel');
Route::get('geteldok', [KlentController::class, 'geteldok'])->name('geteldok');
Route::get('garizantal', [KlentController::class, 'garizantal'])->name('garizantal');
Route::get('garizantalshuc', [KlentController::class, 'garizantalshuc'])->name('garizantalshuc');
Route::get('garizantaldok', [KlentController::class, 'garizantaldok'])->name('garizantaldok');
Route::get('garizantalshucdok', [KlentController::class, 'garizantalshucdok'])->name('garizantalshucdok');
Route::get('tbody2clent', [KlentController::class, 'tbody2clent'])->name('tbody2clent');

